=== Alix29/piston/pistondocs/xml/doc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://piston.googlecode.com/svn/trunk/ns/doc"
    xmlns:d="http://piston.googlecode.com/svn/trunk/ns/doc">
    <xs:element name="doc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="shortDescription" type="d:xhtml"/>
                <xs:element name="longDescription" minOccurs="0" maxOccurs="1" type="d:xhtml"/>
                <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:xhtml"/>
                <xs:element name="constructors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="constructor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="arguments" type="d:arguments"/>
                                        <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:xhtml"/>
                                    </xs:sequence> 
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="validValue" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="default" use="optional" type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="readonly" type="xs:boolean" use="optional"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="methods">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="method" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="returns" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string"/>
                                                    <xs:element name="description" type="d:xhtml"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="arguments" type="d:arguments" minOccurs="1" maxOccurs="unbounded"/>
                                        <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:methodExample"/>
                                    </xs:sequence> 
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="arguments">
        <xs:sequence>
            <xs:element name="argument" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="type" type="xs:string"/>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="description" type="d:xhtml"/>
                    </xs:sequence>
                    <xs:attribute name="optional" type="xs:boolean" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="static" use="optional" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="xhtml" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="methodExample" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
        <xs:attribute name="static" use="optional" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== Alix29/piston/pistondocs/doc/Logan/File/File.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:doc xmlns:d="http://piston.googlecode.com/svn/trunk/ns/doc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://piston.googlecode.com/svn/trunk/ns/doc http://piston.googlecode.com/svn/trunk/pistondocs/xml/doc.xsd"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <name>Logan.File</name>
    <shortDescription>
        The File object represents a File.<div></div>
        It allows you create, read, write, delete or otherwise modify a file.
    </shortDescription>
    <constructors>
        <constructor>
            <description>Creates a new File object</description>
            <arguments>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File();
f.path = "text.txt";]]>
            </example>
            <example><![CDATA[
var f = new Logan.File({ "path" : "text.txt" });]]>
            </example>
        </constructor>
        <constructor>
            <description>Creates a new File object with the given path</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the file</description>
                </argument>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");]]>
            </example>
        </constructor>
    </constructors>
    <properties>
        <property readonly="false">
            <type>String</type>
            <name>path</name>
            <description>The full path to the file</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
    </properties>
    <methods>
        <method>
            <name>exists</name>
            <description>Returns true if the file exists, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if the file exists, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the file</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");

f.exists();    // true]]>
            </example>
            <example static="true"><![CDATA[
Logan.File.exists("test.txt");    // true]]>
            </example>            
        </method>
        <method>
            <name>isDirectory</name>
            <description>Returns true if a directory, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if a directory, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The path to check.</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");

f.isDirectory()        // false]]>
            </example>
            <example static="true"><![CDATA[
Logan.File.isDirectory("test.txt");    // false]]>
            </example>
        </method>
        <method>
            <name>isFile</name>
            <description>Returns true if a file, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if a file, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The path to check.</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");

f.isFile()        // true]]>
            </example>
            <example static="true"><![CDATA[
Logan.File.isFile("test.txt");    // true]]>
            </example>
        </method>
        <method>
            <name>readAll</name>
            <description>Will read and return the entire file as a String</description>
            <returns>
                <type>String</type>
                <description>The contents of the file as a String</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the file</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");

f.readAll();    // contents of test.txt]]>
            </example>
            <example static="true"><![CDATA[
Logan.File.readAll("test.txt");    // contents of test.txt]]>
            </example>
        </method>
        <method>
            <name>size</name>
            <description>Returns the size of the file in bytes</description>
            <returns>
                <type>Number</type>
                <description>The size of the file in bytes</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the file</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Logan.File("test.txt");    // Contents: contents of test.txt

f.size();    // 20]]>
            </example>
            <example static="true"><![CDATA[
Logan.File.size("test.txt");    // 20]]>
            </example>
        </method>
    </methods>
</d:doc>

=== Alix29/piston/trunk/pistondocs/xml/Logan.HTTPRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:doc xmlns:d="http://www.telparia.com/loganmonkey-doc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.telparia.com/loganmonkey-doc doc.xsd"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <name>Logan.HTTPRequest</name>
    <shortDescription>
        The HTTPRequest object represents an HTTP request.<div></div>
        It allows you construct an HTTP request, send the request and receive an HTTP response
    </shortDescription>
    <constructors>
        <constructor>
            <description>Creates a new HTTPRequest object</description>
            <arguments>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
        </constructor>
    </constructors>
    <properties>
        <property readonly="false">
            <type>String</type>
            <name>protocol</name>
            <description>The protocol of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>http</validValue>
            <validValue>https</validValue>
            <validValue>ftp</validValue>
            <validValue>ftps</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>username</name>
            <description>The username of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>password</name>
            <description>The password of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>host</name>
            <description>The host address of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>Number</type>
            <name>port</name>
            <description>The port number of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>path</name>
            <description>The path of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>Object</type>
            <name>query</name>
            <description>The query parameters of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>{ * : *, ... }</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>anchor</name>
            <description>The anchor of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
    </properties>
    <methods>
        <method>
            <name>getQueryParameter</name>
            <description>Returns the value of a query parameter</description>
            <returns>
                <type>String</type>
                <description>The value of the query parameter requested.<div/>null if no such query key exists</description>
            </returns>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to get</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html?level=47&apple=red");

u.getQueryParameter("level");    // 47]]>
            </example>
        </method>
        <method>
            <name>setQueryParameter</name>
            <description>Sets a query parameter</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to set</description>
                </argument>
                <argument>
                    <type>String</type>
                    <name>value</name>
                    <description>The value you want to set the query key to</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html");
u.setQueryParameter("level", "47");
u.setQueryParameter("apple", "red");

u.toString();    // http://google.com/path/index.html?level=47&apple=red]]>
            </example>
        </method>
        <method>
            <name>unsetQueryParameter</name>
            <description>Unsets a query parameter</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to unset</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html?level=47&apple=red");
u.unsetQueryParameter("level");

u.toString();    // http://google.com/path/index.html?apple=red]]>
            </example>
        </method>
        <method>
            <name>toString</name>
            <description>Returns the full URL as a string</description>
            <returns>
                <type>String</type>
                <description>The full URL as a string.</description>
            </returns>
            <arguments></arguments>
            <example><![CDATA[
var u = new Logan.URL();
u.protocol = "http";
u.host = "google.com";
u.path = "/path/index.html";

u.toString();    // http://google.com/path/index.html]]>
            </example>
        </method>
    </methods>
</d:doc>

=== Alix29/piston/trunk/pistondocs/doc/Piston/Directory/Directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:doc xmlns:d="http://piston.googlecode.com/svn/trunk/ns/doc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://piston.googlecode.com/svn/trunk/ns/doc http://piston.googlecode.com/svn/trunk/pistondocs/xml/doc.xsd"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <name>Piston.Directory</name>
    <shortDescription>
        The Directory object represents a Directory.<div></div>
        It allows you list sub files and directories.
    </shortDescription>
    <constructors>
        <constructor>
            <description>Creates a new Directory object</description>
            <arguments>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Piston.Directory();
f.path = "/tmp";]]>
            </example>
            <example><![CDATA[
var f = new Piston.Directory({ "path" : "/tmp" });]]>
            </example>
        </constructor>
        <constructor>
            <description>Creates a new Directory object with the given path</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the directory</description>
                </argument>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Piston.Directory("/tmp");]]>
            </example>
        </constructor>
    </constructors>
    <properties>
        <property readonly="false">
            <type>String</type>
            <name>path</name>
            <description>The full path to the directory</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
    </properties>
    <methods>
        <method>
            <name>exists</name>
            <description>Returns true if the directory exists, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if the directory exists, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The full or relative path to the directory</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Piston.Directory("/tmp");

f.exists();    // true]]>
            </example>
            <example static="true"><![CDATA[
Piston.Directory.exists("/tmp");    // true]]>
            </example>            
        </method>
        <method>
            <name>isDirectory</name>
            <description>Returns true if a directory, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if a directory, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The path to check.</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Piston.Directory("/tmp");

f.isDirectory()        // true]]>
            </example>
            <example static="true"><![CDATA[
Piston.Directory.isDirectory("/tmp");    // true]]>
            </example>
        </method>
        <method>
            <name>isFile</name>
            <description>Returns true if a file, false otherwise</description>
            <returns>
                <type>Boolean</type>
                <description>true if a file, false otherwise</description>
            </returns>
            <arguments/>
            <arguments static="true">
                <argument>
                    <type>String</type>
                    <name>path</name>
                    <description>The path to check.</description>
                </argument>
            </arguments>
            <example><![CDATA[
var f = new Piston.Directory("/tmp");

f.isFile()        // false]]>
            </example>
            <example static="true"><![CDATA[
Piston.Directory.isFile("/tmp");    // false]]>
            </example>
        </method>
    </methods>
</d:doc>
