=== Alix29/piston/pistondocs/xml/doc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://piston.googlecode.com/svn/trunk/ns/doc"
    xmlns:d="http://piston.googlecode.com/svn/trunk/ns/doc">
    <xs:element name="doc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="shortDescription" type="d:xhtml"/>
                <xs:element name="longDescription" minOccurs="0" maxOccurs="1" type="d:xhtml"/>
                <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:xhtml"/>
                <xs:element name="constructors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="constructor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="arguments" type="d:arguments"/>
                                        <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:xhtml"/>
                                    </xs:sequence> 
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="validValue" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="default" use="optional" type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="readonly" type="xs:boolean" use="optional"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="methods">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="method" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="d:xhtml"/>
                                        <xs:element name="returns" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string"/>
                                                    <xs:element name="description" type="d:xhtml"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="arguments" type="d:arguments" minOccurs="1" maxOccurs="unbounded"/>
                                        <xs:element name="example" minOccurs="0" maxOccurs="unbounded" type="d:methodExample"/>
                                    </xs:sequence> 
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="arguments">
        <xs:sequence>
            <xs:element name="argument" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="type" type="xs:string"/>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="description" type="d:xhtml"/>
                    </xs:sequence>
                    <xs:attribute name="optional" type="xs:boolean" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="static" use="optional" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="xhtml" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="methodExample" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
        <xs:attribute name="static" use="optional" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== Alix29/piston/trunk/pistondocs/doc/Logan/URL/URL.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:doc xmlns:d="http://www.telparia.com/loganmonkey-doc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.telparia.com/loganmonkey-doc file:/mnt/deck/DevLab/loganmonkey/loganmonkey-docs/xml/doc.xsd"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <name>Logan.URL</name>
    <shortDescription>
        The URL object represents a URL.<div></div>
        It allows you parse, construct and manipulate the seperate parts of the URL easily
    </shortDescription>
    <longDescription>
        You can pass to the constructor a URL as a string which will parsed automatically<div></div>
        At that point you can access the individual <a href="#Properties">Properties</a> of the object to read or manipulate the URL<div></div>
    </longDescription>
    <example><![CDATA[
var u = new Logan.URL("http://google.com:8080/hello/index.html");
u.host           // google.com
u.port           // 8080

u.host = "yahoo.com";
u.toString();    // http://yahoo.com:8080/hello/index.html

u.port = null;
u.setQueryParameter("level", "47");
u.toString();    // http://yahoo.com/hello/index.html?level=47]]>  
    </example>
    <constructors>
        <constructor>
            <description>Creates a new URL object</description>
            <arguments>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL();
u.host = "google.com";
u.protocol = "http";

u.toString();    // http://google.com]]>
            </example>
            <example><![CDATA[
var u = new Logan.URL({ "protocol" : "http", "host" : "google.com" });

u.toString();    // http://google.com]]>
            </example>
        </constructor>
        <constructor>
            <description>Creates a new URL object with the given url</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>url</name>
                    <description>The initial URL to parse</description>
                </argument>
                <argument optional="true">
                    <type>Object</type>
                    <name>propertyMap</name>
                    <description>The initial set of <a href="#Properties">Properties</a> to set</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com");
u.path = "/hello/index.html";

u.toString();    // http://google.com/hello/index.html]]>
            </example>
            <example><![CDATA[
var u = new Logan.URL("http://google.com", { "path" : "/hello/index.html" });

u.toString();    // http://google.com/hello/index.html]]>
            </example>
        </constructor>
    </constructors>
    <properties>
        <property readonly="false">
            <type>String</type>
            <name>protocol</name>
            <description>The protocol of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>http</validValue>
            <validValue>https</validValue>
            <validValue>ftp</validValue>
            <validValue>ftps</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>username</name>
            <description>The username of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>password</name>
            <description>The password of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>host</name>
            <description>The host address of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>Number</type>
            <name>port</name>
            <description>The port number of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>path</name>
            <description>The path of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
        <property readonly="false">
            <type>Object</type>
            <name>query</name>
            <description>The query parameters of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>{ * : *, ... }</validValue>
        </property>
        <property readonly="false">
            <type>String</type>
            <name>anchor</name>
            <description>The anchor of the URL</description>
            <validValue default="true">null</validValue>
            <validValue>*</validValue>
        </property>
    </properties>
    <methods>
        <method>
            <name>getQueryParameter</name>
            <description>Returns the value of a query parameter</description>
            <returns>
                <type>String</type>
                <description>The value of the query parameter requested.<div/>null if no such query key exists</description>
            </returns>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to get</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html?level=47&apple=red");

u.getQueryParameter("level");    // 47]]>
            </example>
        </method>
        <method>
            <name>setQueryParameter</name>
            <description>Sets a query parameter</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to set</description>
                </argument>
                <argument>
                    <type>String</type>
                    <name>value</name>
                    <description>The value you want to set the query key to</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html");
u.setQueryParameter("level", "47");
u.setQueryParameter("apple", "red");

u.toString();    // http://google.com/path/index.html?level=47&apple=red]]>
            </example>
        </method>
        <method>
            <name>unsetQueryParameter</name>
            <description>Unsets a query parameter</description>
            <arguments>
                <argument>
                    <type>String</type>
                    <name>key</name>
                    <description>The key of the query parameter to unset</description>
                </argument>
            </arguments>
            <example><![CDATA[
var u = new Logan.URL("http://google.com/path/index.html?level=47&apple=red");
u.unsetQueryParameter("level");

u.toString();    // http://google.com/path/index.html?apple=red]]>
            </example>
        </method>
        <method>
            <name>toString</name>
            <description>Returns the full URL as a string</description>
            <returns>
                <type>String</type>
                <description>The full URL as a string.</description>
            </returns>
            <arguments></arguments>
            <example><![CDATA[
var u = new Logan.URL();
u.protocol = "http";
u.host = "google.com";
u.path = "/path/index.html";

u.toString();    // http://google.com/path/index.html]]>
            </example>
        </method>
    </methods>
</d:doc>
